site_name: CRF Splitter User Documentation
docs_dir: '.'
site_dir: '../site'  # This will be a temporary build folder
nav:
    - Home: index.md
    - CRF: 
      - 'Scan Split & Upload': crfsplit.md
theme: readthedocs
